package northwind.domain.customer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2022-06-17T16:04:09.624+05:30
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://domain.northwind/customer", name = "CustomersPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomersPort {

    @WebMethod(operationName = "GetCustomer")
    @WebResult(name = "GetCustomerResponse", targetNamespace = "http://domain.northwind/customer", partName = "GetCustomerResponse")
    public GetCustomerResponse getCustomer(

        @WebParam(partName = "GetCustomerRequest", name = "GetCustomerRequest", targetNamespace = "http://domain.northwind/customer")
        GetCustomerRequest getCustomerRequest
    );

    @WebMethod(operationName = "UpdateCustomer")
    @WebResult(name = "UpdateCustomerResponse", targetNamespace = "http://domain.northwind/customer", partName = "UpdateCustomerResponse")
    public UpdateCustomerResponse updateCustomer(

        @WebParam(partName = "UpdateCustomerRequest", name = "UpdateCustomerRequest", targetNamespace = "http://domain.northwind/customer")
        UpdateCustomerRequest updateCustomerRequest
    );

    @WebMethod(operationName = "DeleteCustomer")
    @WebResult(name = "DeleteCustomerResponse", targetNamespace = "http://domain.northwind/customer", partName = "DeleteCustomerResponse")
    public DeleteCustomerResponse deleteCustomer(

        @WebParam(partName = "DeleteCustomerRequest", name = "DeleteCustomerRequest", targetNamespace = "http://domain.northwind/customer")
        DeleteCustomerRequest deleteCustomerRequest
    );

    @WebMethod(operationName = "CreateCustomer")
    @WebResult(name = "CreateCustomerResponse", targetNamespace = "http://domain.northwind/customer", partName = "CreateCustomerResponse")
    public CreateCustomerResponse createCustomer(

        @WebParam(partName = "CreateCustomerRequest", name = "CreateCustomerRequest", targetNamespace = "http://domain.northwind/customer")
        CreateCustomerRequest createCustomerRequest
    );
}
