package northwind.domain.customer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2022-06-17T16:04:09.678+05:30
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "CustomersPortService",
                  wsdlLocation = "file:/C:/Users/I542324/git/soap-basic/soap-basic-auth-cxf-client/src/main/resources/customers.wsdl",
                  targetNamespace = "http://domain.northwind/customer")
public class CustomersPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://domain.northwind/customer", "CustomersPortService");
    public final static QName CustomersPortSoap11 = new QName("http://domain.northwind/customer", "CustomersPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/I542324/git/soap-basic/soap-basic-auth-cxf-client/src/main/resources/customers.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomersPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/I542324/git/soap-basic/soap-basic-auth-cxf-client/src/main/resources/customers.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomersPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomersPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomersPortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomersPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomersPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomersPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CustomersPort
     */
    @WebEndpoint(name = "CustomersPortSoap11")
    public CustomersPort getCustomersPortSoap11() {
        return super.getPort(CustomersPortSoap11, CustomersPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomersPort
     */
    @WebEndpoint(name = "CustomersPortSoap11")
    public CustomersPort getCustomersPortSoap11(WebServiceFeature... features) {
        return super.getPort(CustomersPortSoap11, CustomersPort.class, features);
    }

}
