//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.13 at 03:24:27 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://domain.northwind/customer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package northwind.domain.customer.wsdl;
